[package]
name = "bitarray"
version = "0.2.0"
edition = "2018"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
license = "MIT"
description = "A const generics driven bit array"
repository = "https://github.com/vadixidav/bitarray"
documentation = "https://docs.rs/bitarray/"
keywords = ["const", "generics", "bit", "array", "hamming"]
categories = ["no-std"]
readme = "README.md"
