[package]
name = "bitarray"
version = "0.1.2"
edition = "2018"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
license = "MIT"
description = "A compile time sized array of bits"
repository = "https://github.com/vadixidav/bitarray"
documentation = "https://docs.rs/bitarray/"
keywords = ["data-structures", "bitarray", "bitmask", "bitmap", "bit"]
readme = "README.md"
